name: Embeddings_Comparator
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/Embeddings_Comparator
  original_url: https://huggingface.co/spaces/Chris4K/Embeddings_Comparator

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"

# Updated: 2026-01-03 14:07:22
